language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install pelican-gist
- pip install ghp-import
- pip install markdown
script:
- make publish
- make github
env:
  global:
  - secure: "okkMiEmXVWCW22CgTKPshF+aq6PRhszY4EeJdX020QarBt50wqcEhm3DKvWImkU5wb0Hd8BMs+/FJdU4grIWnKP90zPBIcDGsR9tiSVXERJnk/ym12bi2rGoQeGfLkCDjq78yyeMzrSjN7dp1Fzsj0dgMh249Dv1IJqWprJtsaH4ACxpFmHin10mPeV92N0pP7E688khyeSSXPTBFnG/fjyp3Hsa/is8k+Zpl6Bgi57e3V7+cNwARTHEH5vmNUL+Q2yByXSwok6f3vpWEoI74TA/c5jqjjJByMKibQKd/PfQPbjwQqWC8gktNTRJ2FgdI1gdMnflHsf2D6l4XrA9AFfNoySKr67lwCmrjCWdoCKVKNUM7JWBADI/OiJh+ShidwPiQ502goZxd2Ebl5lrtaG4z9gPf939d8lQJ+9t7DPczg7EIDAcL4iaJQoFln76y6zqhaF3Hf24JrUjvgnSbfhEl+y1bVyqWakrou3bQrpqPJNe1elvygzilZXxEJQzo9V2Xe+8xnm7G0dakjOer9uNpsP56vWf0G9nGFI338+hwsKqBtxTAiAB4BH3tIU6em3bWo8o6qWlbvI4K6pF4eIf9yvzzZiUQI6QE83W36SlOqoUdPQPSA9/m8u/I3da67LHrDCqtGXQFBZz7/fgNt9XyJNUcSIyOjYmTNInqMk="
