language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install pelican-gist
- pip install ghp-import
- pip install markdown
script:
- make publish
- make github
env:
  global:
  - secure: "t5RcLsVIjQH+B6mFn8l4fwwlmutv6Q1WIdPW6yMhEHuP2xQ/nkR5QkEcEdo/GtnbLKwxeTnmeiKAwwwoO+Ed3n3NqTKgRKtH2sUgWUKcnzEEU/0uHTyVD9Vr8jcPSVJj2S7FjGTXzdzhZ0GNpAGYmKHgZo4lEBYstjoOs83cie3+hPvGqdIESI7Lm3AWevARyoF82cP0N9ixoupfcM308a8FiQBtQPk+/N2jG5kjLPzSFFdzuywSz+t1nt4Jt9z4Imw+e7FBDLNqVm74uOFpkNPyD6IUkADi8JLrvV65+0ObGAPMml1H38wB8+m/cpcKBSmIGeYbbUNTWGqBPTGCRwVO3RG1IPY3hdYxwzoiChrEQ83A1g+J57mX7ethlCmHRtaoMnTRr5zk7/yoLfSE+apOpV8oZElMVN0C7rrPhec0dzYKPmHbbwrROGjCh+umAGGVJDJDL5SVDzCckNPlRbZIC2uOztusyJh5TTsvJ55yfZvo9Og5UpHDFt5TMOmdKV1+fYLcDc/xFDpU0N2lakbBz57cP/qW1fwyoFluPBvfu40cDJx7u7rE9UT9OX8Oozsr1atch/NkKx4C1eutPIf5IpAX0SlczsdvpKHImXnSsEWmbCcsenpW7E9B8VcWSrxB7i9nyBPOzgR3Fa+azDs/LkncF4HxVAyjR8jFh7U="
